<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RootNamespace>CabSpan</RootNamespace>
    <AssemblyName>CabSpan</AssemblyName>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <ApplicationIcon>Assets\CabSpan.ico</ApplicationIcon>
    <RepositoryUrl>https://github.com/itsjuztin/CabSpan</RepositoryUrl>
    <DebugType>embedded</DebugType>
    <PathMap>$(MSBuildProjectDirectory)=/src</PathMap>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\CabSpan.ico" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>


